### ISSUE TITLE
Run all test methods get an error

### ISSUE THREAD

**Issue by jairzh** [kevinohara80/dmc#40]
I tried to run all test methods using `dmc test -a --coverage -o myorg`, but I got the following error:

```
[dmc] using org: myorg
[dmc] processing 145 records
/usr/local/lib/node_modules/dmc/commands/test.js:40
          var td = r.SymbolTable.tableDeclaration;
                                ^

TypeError: Cannot read property 'tableDeclaration' of null
    at /usr/local/lib/node_modules/dmc/commands/test.js:40:33
    at arrayMap (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:1406:25)
    at map (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:6710:14)
    at interceptor (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:12240:26)
    at thru (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:5927:26)
    at baseWrapperValue (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:2768:30)
    at LazyWrapper.lazyValue [as value] (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:1077:16)
    at baseWrapperValue (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:2761:25)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/dmc/node_modules/lodash/index.js:6124:14)
    at /usr/local/lib/node_modules/dmc/commands/test.js:65:10
    at Object.resolve (/usr/local/lib/node_modules/dmc/node_modules/nforce/lib/promises.js:25:20)
    at processResponse (/usr/local/lib/node_modules/dmc/node_modules/nforce/index.js:1020:25)
    at Request._callback (/usr/local/lib/node_modules/dmc/node_modules/nforce/index.js:1078:7)
    at Request.self.callback (/usr/local/lib/node_modules/dmc/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
```

**Comment by kevinohara80** [comment]
Hey, sorry for the delay in getting around to testing this. I can't reproduce this. Can you isolate this to a particular type of file or something? When I run `dmc test -a --coverage -o myorg` across my org the tests run fine.

Also, what version are you on. Can you try the latest (`v1.5.1`)?

**Comment by jairzh** [comment]
@kevinohara80 Thanks for following up my issue. I upgraded my dmc to the `v1.5.1` and `run dmc test -a --coverage -o myorg`, it doesn't work for me, I got the same error.
