### ISSUE TITLE
Proposal For .dmcignore 

### ISSUE THREAD

**Issue by duncanfinney** [kevinohara80/dmc#5]
It would be useful to have the option to ignore certain files in the globbing pattern.

Most notably, mm.log files:

```
[dmc] * src/classes/UserDetails.cls
[dmc] * src/classes/UserDetails.cls-meta.xml
[dmc] * src/classes/Visualization.cls
[dmc] * src/classes/Visualization.cls-meta.xml
[dmc] * src/classes/Visualization_Test.cls
[dmc] * src/classes/Visualization_Test.cls-meta.xml
[dmc] * src/classes/mm.log
[err] missing file: src/classes/mm.log-meta.xml
[dmc] * src/triggers/MetricAssignmentTrigger.trigger
[dmc] * src/triggers/MetricAssignmentTrigger.trigger-meta.xml
[dmc] * src/triggers/MetricFilterTrigger.trigger
[dmc] * src/triggers/MetricFilterTrigger.trigger-meta.xml
[dmc] * src/triggers/MetricTrigger.trigger
[dmc] * src/triggers/MetricTrigger.trigger-meta.xml
[dmc] * src/triggers/ScorecardLogTrigger.trigger
[dmc] * src/triggers/ScorecardLogTrigger.trigger-meta.xml
[dmc] * src/triggers/UserAssignmentTrigger.trigger
[dmc] * src/triggers/UserAssignmentTrigger.trigger-meta.xml
[dmc] * src/triggers/mm.log
[err] missing file: src/triggers/mm.log-meta.xml
[dmc] * src/permissionsets/Scorecard_Admin.permissionset
[dmc] * src/permissionsets/Scorecard_Manager.permissionset
[dmc] * src/permissionsets/Scorecard_User.permissionset
[dmc] * src/permissionsets/mm.log
[err] missing file: src/staticresources/email.resource-meta.xml
[err] missing file: src/staticresources/mm.log-meta.xml
[err] missing file: src/components/mm.log-meta.xml
[err] missing file: src/pages/mm.log-meta.xml
[err] missing file: src/classes/mm.log-meta.xml
[err] missing file: src/triggers/mm.log-meta.xml
[err] cannot deploy - missing files
Error: cannot deploy - missing files
    at /Users/duncan/.nvm-fish/v0.12.2/lib/node_modules/dmc/commands/deploy.js:437:25
    at /Users/duncan/.nvm-fish/v0.12.2/lib/node_modules/dmc/node_modules/async/lib/async.js:251:17
    at /Users/duncan/.nvm-fish/v0.12.2/lib/node_modules/dmc/node_modules/async/lib/async.js:200:33
    at /Users/duncan/.nvm-fish/v0.12.2/lib/node_modules/dmc/node_modules/async/lib/async.js
```

**Comment by kevinohara80** [comment]
Good call. Will implement.

**Comment by kevinohara80** [comment]
@duncanfinney this works now :)
